//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.BasedeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public short ID_Compra { get; set; }
        public Nullable<byte> Cantidad { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<byte> ID_Prov { get; set; }
        public Nullable<byte> ID_Corte { get; set; }
        public Nullable<short> Peso { get; set; }
        public decimal Total { get; set; }
    
        public virtual Cortes Cortes { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
