//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.BasedeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public short ID_Gasto { get; set; }
        public System.DateTime FechaGasto { get; set; }
        public decimal Monto { get; set; }
        public Nullable<byte> ID_TG { get; set; }
    
        public virtual TipodeGastos TipodeGastos { get; set; }
    }
}
