//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID_Venta { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal TotVenta { get; set; }
        public decimal TotTarjeta { get; set; }
    }
}
